### ISSUE TITLE
is this lib supposed to be better performance than httpbeast ?

### ISSUE THREAD

**Issue by bung87** [disruptek/httpleast#1]

**Comment by disruptek** [comment]
This is a reference implementation that I've used to test performance of different dispatcher ideas.  If you want to make this demonstration server faster, here are a couple features you'll want to change in the reference dispatcher:

- register/deregister your listeners rarely
- alloc/dealloc your continuations rarely

With only minor tweaks, I've seen performance within 15% of httpbeast single-threaded.  On 12 threads, **httpbeast** sees a ~60% performance increase over a single thread.  You can [look at the cps repo example to see trivial multi-threaded cps](https://github.com/disruptek/cps/blob/master/examples/threadpool.nim); httpbeast won't offer much of a contest here at all.

But I'm not Google and I don't need to serve 2,000,000 requests per second, so my personal goal for a CPS-based web-server is one that I can comingle with other continuations inside my program so I can service clients at my convenience, without impacting the performance of my application.

**Comment by disruptek** [comment]
It's about 2x as fast as `httpbeast` on one thread and 3x as fast on two threads.  Latency is 3-5x better as load scales.  Maybe I'll add a table to the README or something.

**Comment by ajusa** [comment]
That would be super cool. I'd also love it if this were provided more as a library rather than a benchmark with hardcoded requests going on. It'd be amazing if I could run Jester on top of this for added performance over httpbeast.
